apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s31j2o1jg-python
  janus-idp.io/tekton: s31j2o1jg-python
  backstage.io/kubernetes-id: s31j2o1jg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s31j2o1jg-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
